// Mirror Index — Learn hub content. Authoring format: body is an array of blocks.
// Inline supports [label](/path) links and *emphasis*.
export const LEARN_ARTICLES = [
  {
    slug: 'the-interference',
    cluster: 'The pattern',
    readMins: 4,
    title: "It's Not Your Potential, It's the Interference | Mirror Index",
    description:
      "A tennis coach worked out fifty years ago why capable people underperform. It explains your love life better than any dating advice you've read.",
    h1: "It's not your potential. It's the interference.",
    dek: 'A fifty-year-old idea from tennis explains your love life better than any dating advice you have read.',
    pillar: true,
    body: [
      { type: 'p', text: "Fifty years ago, a tennis coach called Timothy Gallwey noticed something odd about his students. Their biggest opponent wasn't across the net. It was the voice in their own head — the flinch before the swing, the *don't mess this up*, the old story about what kind of player they were. He put it into a sentence that has quietly travelled the world since: performance equals potential minus interference." },
      { type: 'p', text: "Not *you're not good enough*. Not *try harder*. Just: something is sitting between what you could do and what you actually do. And most of the time, you can't see it." },
      { type: 'p', text: "Psychologists took the idea and ran with it — there's a whole tradition of emotional-intelligence coaching built on top of it, helping people notice the attitudes running underneath their behaviour. Beliefs like *I have to get this right* or *I'm valuable when I'm useful*, usually installed early, usually running silently, usually mistaken for personality." },
      { type: 'p', text: "Here's the strange part. We've known all this for decades. And almost nobody applies it to the one part of life where the stakes are highest." },
      { type: 'h2', text: 'The same voice goes on the date' },
      { type: 'p', text: "The interference doesn't switch off when you fall for someone. The same beliefs that trip people up everywhere else are precisely the machinery that chooses your partners. Same head. Same old stories. Much higher stakes." },
      { type: 'p', text: "You've seen relationship interference, even if you've never called it that. It's staying two years too long because leaving feels like breaking your word — that's an attitude about loyalty making your decisions for you. It's giving endlessly and calling it love, because somewhere along the way your sense of worth picked up a condition: *I am loved when I am needed.* It's the pull toward the thrilling, unavailable one at week six — what we call the [shadow attraction](/mirror-index/archetypes) — which isn't bad luck, and isn't chemistry. It's an old belief, choosing on your behalf." },
      { type: 'p', text: "Rewrite Gallwey for love and it comes out something like this: *satisfaction = compatibility − pattern.* Your capacity for a good relationship was never the problem. The pattern is the interference." },
      { type: 'h2', text: "Why knowing about it hasn't fixed it" },
      { type: 'p', text: "Here's the uncomfortable bit, and the coaching tradition is blunt about it: information doesn't change behaviour. You can know your attachment style, know your type is bad for you, know exactly how this one ends — and do it again anyway. Knowledge sits on the surface. Patterns live deeper, in the attitudes and habits knowledge doesn't reach on its own." },
      { type: 'p', text: "Which is why one more article about red flags hasn't changed who you're drawn to. (Including, in fairness, this one.) Insight only becomes useful when it gets specific and personal — when the vague sense that *I keep doing this* becomes a named thing you can actually argue with." },
      { type: 'quote', text: "You cannot argue with a pattern you haven't named." },
      { type: 'h2', text: 'What a mirror is for' },
      { type: 'p', text: "Naming it is the job [Mirror Index](/mirror-index/how-it-works) was built to do — and, just as importantly, the only job it claims." },
      { type: 'p', text: "The assessment maps your pattern properly: who you are as a partner, who you say you want, the gap between those two answers, and the shadow type your interference keeps choosing for you. The EI Mirror goes a layer deeper and reads the capacities underneath — self-awareness, self-management, how you actually handle what you feel — because those were always going to decide how love goes, whatever else they decide along the way." },
      { type: 'p', text: "But we'll say plainly what the coaching tradition has always known: a report is not the fix. People don't change by reading about themselves; they change through honest conversations — with a partner, a coach, a therapist, or the hardest audience of all, themselves on a quiet evening. An assessment is never a verdict and never an answer. At its best, it's the [start of the right conversation](/mirror-index/philosophy): a map of where your interference lives, so you stop arguing with the wrong thing." },
      { type: 'p', text: "You've spent years working around a pattern you couldn't quite see. Naming it takes twelve minutes." },
      { type: 'note', text: "Mirror Index is a self-reflection tool, not a clinical diagnostic, and not a substitute for coaching or therapy — it's designed to make both work better. With a nod to T. Gallwey's *The Inner Game of Tennis* and S. Neale, L. Spencer-Arnell & L. Wilson's *Emotional Intelligence Coaching* (Kogan Page)." },
    ],
    cta: { title: 'Name the pattern in twelve minutes.', label: 'Meet your archetype — free' },
  },
  {
    slug: 'the-signal-box',
    cluster: "What it's for",
    readMins: 5,
    title: 'The Signal Box: What an Assessment Is Actually For | Mirror Index',
    description:
      "An assessment can't drive your love life and shouldn't plan your route. Its real job is older, humbler, and more useful — and a Victorian railway explains it.",
    h1: 'The signal box: what an assessment is actually for',
    dek: "An assessment can't drive your love life and shouldn't plan your route. A Victorian railway explains the humbler, more useful job it can do.",
    body: [
      { type: 'p', text: "Before the age of automation, every stretch of railway line was watched over by a signal box: a small building raised above the track, staffed by one person whose job was to know the state of the network. Which trains were running. How fast, how close, in which direction. The signalman didn't drive anything. He didn't decide where anyone was going. He read the information coming in and set the signals and the points accordingly — and the whole system depended on him being well informed." },
      { type: 'p', text: "I wrote about signal boxes in another context, in a book called *Tracks*, about why lives don't follow their timetables. But the longer I've spent building relationship assessments, the more I've realised the signal box answers a question I get asked constantly, usually with one eyebrow raised: *what is a personality assessment actually for?*" },
      { type: 'p', text: "Because there are two jobs people assign to assessments, and both are wrong." },
      { type: 'h2', text: 'The two wrong jobs' },
      { type: 'p', text: "The first wrong job is *driver*. This is the quiz-magazine fantasy: answer these questions and we'll tell you what to do. Who to date. Who to leave. Whether he's the one. Any instrument that accepts this job is lying to you — not because the questions are bad, but because no set of questions can occupy your seat. You drive. You were always going to drive. An assessment that grabs the controls has failed at something more important than accuracy." },
      { type: 'p', text: "The second wrong job is *route planner*. This is the more respectable fantasy: the assessment as authority, handing down the optimal path. It flatters the instrument and infantilises the person. It's also where most \u201cmatching algorithms\u201d quietly live — the promise that the route can be computed for you, if you'll just keep swiping and let the system optimise." },
      { type: 'p', text: "Notice what both fantasies have in common: they move the decision out of your hands. And notice how the dating world is arranged almost entirely around them — apps that promise to drive, algorithms that promise to plan, quizzes that promise a verdict. Then notice how you actually feel after two years of that: not more certain. Just more tired, and strangely less informed about yourself than when you started." },
      { type: 'h2', text: 'The third job' },
      { type: 'p', text: "The signalman's job is the third option, and it's the only one an honest assessment can hold: *improve the information reaching the person who sets the points.*" },
      { type: 'p', text: "You already occupy the signal box of your own relational life. You always have. The problem was never that someone else should be in there — it's that the information coming in is terrible. Attraction reports in late, and lies about its reasons. Patterns run silently for a decade before announcing themselves. The friction of a wrong fit — that low, persistent grinding of a relationship that's still moving but costing more than it should — is real long before you have language for it. You've been setting points in the dark and calling the results your love life." },
      { type: 'p', text: "Good signalling data, in this context, looks like something specific. It looks like knowing who you are as a partner — not aspirationally, but as measured. It looks like seeing who you *say* you want, held up next to that, with the gap between the two made visible, because the gap is where most of the useful information lives. And it looks like having your [shadow named](/mirror-index/archetypes): the type you keep choosing that keeps not working, which isn't bad luck and isn't chemistry, but a pattern that has been driving from the back seat." },
      { type: 'p', text: "That is the whole of what [Mirror Index](/mirror-index/how-it-works) attempts. Not the driver. Not the route planner. Instrumentation for the signal box — a feed of honest information into a room where you, and only you, set the points." },
      { type: 'h2', text: "What the box can't see" },
      { type: 'p', text: "Honesty demands one more admission, and it's one no instrument likes making: there are things the signalling never shows." },
      { type: 'p', text: "The clearest is timing. Two people can be genuinely, measurably right for each other and meet in the wrong year — one mid-repair, one mid-departure — and no assessment on earth will detect it, because instruments measure persons and timing belongs to lives. If you've lost someone that way, you know it's a loss with no clean name, and you deserve better than a report pretending it could have been foreseen. It couldn't. Some things reach the signal box only as they happen." },
      { type: 'p', text: "An assessment that admits this is not weaker for it. A signalman who knows the limits of his information is the only kind worth having." },
      { type: 'h2', text: 'The points are yours' },
      { type: 'p', text: "So: [no verdicts here](/mirror-index/philosophy). No route handed down, no \u201cthe one\u201d computed, nobody reaching for your controls. Just the offer every good signal box makes — better information, arriving before the decision instead of after it, in time to be useful." },
      { type: 'p', text: "You've been running the network for years. You've simply been running it on poor data." },
      { type: 'quote', text: 'Twelve minutes. Fifty questions. Clearer signals.' },
      { type: 'note', text: "Mirror Index is a self-reflection tool, not a clinical diagnostic, and not a substitute for coaching or therapy. The railway thinking comes from the founder's book *Tracks: Why your life didn't follow the timetable — and why that's the better story*." },
    ],
    cta: { title: 'Better information, before the decision.', label: 'Meet your archetype — free' },
  },
  {
    slug: 'why-you-keep-choosing-the-same-type',
    cluster: 'The pattern',
    readMins: 5,
    title: 'Why You Keep Choosing the Same Type | Mirror Index',
    description:
      "It feels like bad luck or bad taste. It's neither. Here's the quiet mechanism behind repeating the same relationship — and how to see it before you do it again.",
    h1: 'Why you keep choosing the same type',
    dek: "It isn't bad luck, and it isn't chemistry. It's a pattern — and patterns can be named.",
    body: [
      { type: 'p', text: "Different face, different city, different app — and somehow, six weeks in, you're standing in the same argument you swore you'd never have again. It's tempting to call it bad luck, or a run of bad taste. It's usually neither. What you're looking at is a pattern, and patterns are far more reliable than luck." },
      { type: 'h2', text: 'The type isn\u2019t random' },
      { type: 'p', text: "The person who lights you up at first is rarely a stranger. They tend to match a template you've been carrying for years — a familiar emotional climate that *feels like home*, even when home wasn't especially safe. Familiarity reads as chemistry. The nervous system relaxes into what it recognises, and calls that relief a spark." },
      { type: 'p', text: "In [Mirror Index](/mirror-index/how-it-works) we call the reliable version of this the *shadow attraction*: the partner-type your archetype is quietly drawn to and reliably struggles with. The Empath drawn to the Challenger who won't stay. The Rock drawn to the Voyager who won't settle. It is not the exception to your love life. For a lot of people, it *is* the plot." },
      { type: 'h2', text: 'Why insight alone hasn\u2019t stopped you' },
      { type: 'p', text: "You may already know your type is bad for you. Knowing has not helped much — and there is a good reason for that. Knowledge sits on the surface; the pull lives underneath, in old attitudes about what love is supposed to feel like. You don't decide to repeat the pattern. The pattern decides, a half-second before you do, and hands you a feeling that looks a lot like desire." },
      { type: 'quote', text: 'You cannot outrun a pattern you have never named.' },
      { type: 'h2', text: 'Naming it is the whole move' },
      { type: 'p', text: "The thing that actually shifts the odds is specificity. Not \u201cI have a type,\u201d but *this* type — named, mapped, with the loop drawn out and the green-flag pattern that breaks it written down. That is what an honest assessment is for. Mirror Index reads two lenses — who you are as a partner and who you think you want — and shows you the gap, the [archetype](/mirror-index/archetypes) you actually are, and the shadow your interference keeps choosing for you." },
      { type: 'p', text: "It will not make the decision for you, and it will not pretend to. A report is a map, not the journey — the start of a better conversation with a partner, a coach, or yourself. But you cannot have that conversation about a pattern you can't yet see. First you name it. Then everything else gets easier." },
      { type: 'p', text: "It takes about twelve minutes, and post-breakup — while the last one still smarts — is the clearest you will ever see it, before the next person makes it invisible again." },
      { type: 'note', text: 'Mirror Index is a self-reflection tool, not a clinical diagnostic, and not a substitute for coaching or therapy.' },
    ],
    cta: { title: 'See the type before you choose it again.', label: 'Take the free read' },
  },
  {
    slug: 'dont-waste-the-breakup',
    cluster: 'The pattern',
    readMins: 5,
    title: "Don't Waste the Breakup — Read the Pattern First | Mirror Index",
    description:
      "There's a short window after a relationship ends when you can see your own pattern clearly. Most people spend it swiping. Here's what to do instead.",
    h1: "Don't waste the breakup",
    dek: "There's a short window after a relationship ends when you can finally see your own pattern. Most people spend it swiping.",
    body: [
      { type: 'p', text: "There is a window that opens after a relationship ends, and almost nobody tells you it's there." },
      { type: 'p', text: "It opens somewhere past the acute stage — after the logistics, after the version of events has been told enough times to hold its shape. What opens isn't happiness; it's *visibility*. For a short while, you can see your own relational life from outside it. The choices, the chemistry, the moment you knew and stayed anyway. While you're in a relationship, the pattern is invisible because you're standing inside it. Once you're deep into the next one, it will be invisible again. In between, and only in between, the fog lifts." },
      { type: 'p', text: "And what does the culture tell you to do with this rare, expensive clarity?" },
      { type: 'p', text: "Get back out there." },
      { type: 'p', text: "Download the apps. Line up the dates. Nothing rebuilds confidence like attention, and nothing wastes the window faster. Because the person swiping three weeks after a breakup is not choosing differently — they are choosing *again*, with the same instincts that chose last time, at the exact moment those instincts are hungriest and least supervised." },
      { type: 'h2', text: 'The post-mortem nobody performs' },
      { type: 'p', text: "When a project fails at work, competent people hold a review. Not to assign blame — to extract the information the failure paid for. Relationships end and we skip this entirely. We perform the *social* post-mortem, of course — the friends, the wine, the agreed narrative of what went wrong with *them*. What we almost never perform is the structural one: what did the ending reveal about how I choose?" },
      { type: 'p', text: "Be careful with that question, because there are two counterfeit versions of it. One is the blame-them reading, which produces a villain and no information. The other is the blame-me reading — *I'm broken, I have a type, I always do this* — which feels like insight and is actually just the villain relocated. Both close the window early. The real question is quieter and more useful: not *who was wrong*, but *what keeps being true?*" },
      { type: 'p', text: "What keeps being true has a shape. Maybe you're the loyal one who stays two years past the point of knowing, because leaving feels like breaking your word. Maybe you're the one who gives until the resentment bill arrives, because somewhere along the line love got wired to being needed. Maybe the thrilling, unavailable one at week six has appeared in three consecutive stories, and you're still calling it coincidence, or chemistry, or bad luck in a city this size." },
      { type: 'p', text: "That recurring character isn't bad luck. In our language, it's your [shadow](/mirror-index/archetypes) — the type your pattern keeps choosing despite the damage — and it is the single most valuable thing a breakup can teach you, if you read for it before the window shuts." },
      { type: 'h2', text: 'Two things the reading is not' },
      { type: 'p', text: "First, it is not a verdict on the relationship that just ended. Some endings aren't pattern at all — some are [timing](/mirror-index/learn/the-signal-box), two people genuinely right for each other in the wrong year, and that loss deserves grief, not analysis. An honest reading knows the difference and doesn't pretend everything is a lesson." },
      { type: 'p', text: "Second, it is not something you can reliably do alone in your head — for the same reason the relationship was hard to see from inside. Unstructured introspection after a breakup has a way of arriving wherever your mood was already going. What the window needs is structure: specific questions, answered honestly, held up in an order you didn't choose. That's what an instrument is for. Not to tell you what your ending meant — to make sure the question gets asked properly while it can still be answered." },
      { type: 'h2', text: 'Twelve minutes, while it still smarts' },
      { type: 'p', text: "This is exactly what [Mirror Index](/mirror-index/how-it-works) was built for, and the post-breakup moment is when it works hardest. Fifty questions about who you are as a partner. The same fifty about who you say you want. The gap between those answers, measured. And the shadow — the recurring character — named to your face, gently, while you can still recognise them from very recent memory." },
      { type: 'p', text: "Then, when you do go back out there — and you will, and you should — you go carrying a map instead of a mood." },
      { type: 'p', text: "The window doesn't stay open. The next person is coming, and they will be lovely, and the fog will roll back in the way it always does. The only question is what you'll know about yourself when they arrive." },
      { type: 'quote', text: "Don't waste the breakup." },
      { type: 'note', text: "Mirror Index is a self-reflection tool, not a clinical diagnostic, and not a substitute for therapy. If the ending you're carrying feels heavier than reflection can hold, a professional is the right next step — and this will still be here after." },
    ],
    cta: { title: 'Read the pattern while you can still see it.', label: 'Meet your archetype — free' },
  },
  {
    slug: 'the-assessment-that-knows-its-place',
    cluster: 'For coaches',
    readMins: 6,
    title: 'The Assessment That Knows Its Place — For Relationship Coaches | Mirror Index',
    description:
      "Most instruments want your client's conversation. A well-behaved assessment hands it to you. What Mirror Index does in a coaching room — and what it refuses to do.",
    h1: 'The assessment that knows its place',
    dek: "Most instruments want your client's conversation. A well-behaved one hands it to you — what Mirror Index does in a coaching room, and what it refuses to do.",
    body: [
      { type: 'p', text: "Every coach has met the client who arrives holding a report like a verdict." },
      { type: 'p', text: "Somewhere online they took an assessment, and now they're an INFJ, or an anxious-avoidant, or a Type Four, and the label has quietly hardened from *description* into *explanation* — and from explanation into excuse. \u201cI can't help it — I'm an initial-string.\u201d You've spent sessions gently prising a client's fingers off a four-letter identity that was supposed to be a doorway and became a wall." },
      { type: 'p', text: "So let me say the strange thing first: I build assessments for a living, and I think your scepticism about assessments is correct. Most instruments in the relationship space are badly behaved. They overclaim their evidence, they flatter to retain, and — the part that matters in your room — they position themselves as the *end* of a conversation rather than the start of one. They want the last word. In coaching, the last word is precisely the thing an instrument must never want." },
      { type: 'h2', text: 'What the first three sessions actually cost' },
      { type: 'p', text: "Here's the practical problem an instrument *should* be solving. A new client arrives with a story about their relational life — polished, plausible, and partial in both senses of the word. You know, because it's your craft, that the story and the pattern are different things, and that the early sessions are largely excavation: getting underneath the account of the last relationship to the structure that produced the last three." },
      { type: 'p', text: "That excavation is skilled work, and some of it can only be done live. But some of it is measurement wearing a conversation costume — and measurement is what instruments are for. A well-designed intake assessment doesn't replace your first three sessions; it compresses the part of them that was always retrieval, so the coaching starts where the coaching matters." },
      { type: 'h2', text: 'What a well-behaved instrument looks like' },
      { type: 'p', text: "Mirror Index was built to a [philosophy](/mirror-index/philosophy) I'd defend in any room of practitioners: an assessment is never a verdict and never an answer. It is a serious conversation starter — structured introspection that earns the client's honesty, and a doorway to deeper work with a professional where that's warranted. A report that thinks it's the intervention has failed. In a coaching context, that philosophy cashes out as four design behaviours." },
      { type: 'p', text: "*It measures the gap, not just the person.* The client answers the same fifty items twice — as who they are, and as who they say they want. The delta between those two profiles is intake gold: it's the distance between the client's self-story and their stated desire, mapped before your first session, with the contradictions already visible." },
      { type: 'p', text: "*It names the shadow.* Each of the six [archetypes](/mirror-index/archetypes) carries a mapped shadow — the type it's drawn to that reliably costs it. Clients recognise their shadow with an immediacy that would take weeks to reach conversationally, and because the *instrument* said it, you're free to be the ally who explores it rather than the authority who accused them of it." },
      { type: 'p', text: "*It's written to be argued with.* Report language is deliberately contestable — \u201cthe questionnaire says X; is that how it actually is?\u201d — because the client arguing with their own report *is* the session. Where the deeper psychometric modules disagree with the client's self-report, we surface the discrepancy as a question, never a correction. The gap gets handed to you, not adjudicated by us." },
      { type: 'p', text: "*It publishes its own limits.* The archetype core is at what we publish as an [Exploratory tier](/mirror-index/science) — theory-grounded, production-ready for self-reflection, evidence base still maturing, and the product says so. The underlying Big Five and EI instruments carry published calibration histories. You'll never be in the position of defending a claim we shouldn't have made, because we didn't make it. And some things we simply refuse: no clinical language, no matching promises, no reading of *timing* — an instrument measures persons, not moments, and any coach knows how much of relational life is timing." },
      { type: 'h2', text: 'The last word' },
      { type: 'p', text: "There's an old railway image I keep returning to: the [signal box](/mirror-index/learn/the-signal-box), where one person reads the state of the network and sets the points. In a coaching engagement, your client is the signalman and you are the one teaching them to read. An instrument's only legitimate role is to improve the information reaching that box. It doesn't drive. It doesn't plan the route. It certainly doesn't take the last word." },
      { type: 'p', text: "That's the whole offer: an assessment that does the measurement, hands you the conversation, and knows its place." },
      { type: 'p', text: "If you'd like to see what that looks like in practice — sample reports, the practitioner view, the white paper with the full methodology — we're inviting a small number of coaches into a pilot." },
      { type: 'note', text: "Mirror Index is a self-reflection instrument, not a clinical tool, and is not validated for diagnosis or high-stakes selection. Practitioner enquiries: the white paper and sample reports are available on request." },
    ],
    cta: { title: 'An assessment that knows its place.', label: 'See Mirror Index for coaches', to: '/mirror-index/for-business' },
  },
];

export const learnBySlug = Object.fromEntries(LEARN_ARTICLES.map((a) => [a.slug, a]));
