"""Three read-mostly analyses on the stored corpus, run as one pass.

1. Correlation matrix of the six Essential archetype scores. Assignment-free, unlike the
   centroid distances in docs/CENTROID_SEPARATION.md: grouping results by whichever score is
   largest guarantees separated centroids by construction, so 1.45 shows the assignment rule is
   self-consistent, not that six item sets measure six things. The correlations test that.
2. Quarantine of low-variation stored results — uniform and two-value answering, generated by
   test runs, not people. Flagged on the result document AND excluded by default here, because a
   flag nothing honours is documentation rather than a control.
3. The MRD suppression rate recomputed with those excluded. The 1.0 that made R1 SEVERE was
   computed across everything, and a session with every item answered identically produces a
   perfectly flat profile, which is exactly what the flat-profile gate suppresses.

Usage: python3 scripts/analyze_stored_corpus.py [--write-flags]
"""
import asyncio
import json
import os
import statistics
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "backend"))

from dotenv import load_dotenv

load_dotenv(os.path.join(ROOT, "backend", ".env"))

from motor.motor_asyncio import AsyncIOMotorClient  # noqa: E402

from services.essential_scoring import ARCHETYPES  # noqa: E402

VARIED_MIN_DISTINCT = 4  # a session answering on fewer than four of the five points is patterned


def pearson(xs, ys):
    n = len(xs)
    mx, my = sum(xs) / n, sum(ys) / n
    num = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    dx = sum((x - mx) ** 2 for x in xs) ** 0.5
    dy = sum((y - my) ** 2 for y in ys) ** 0.5
    return num / (dx * dy) if dx and dy else 0.0


async def main(write_flags: bool):
    db = AsyncIOMotorClient(os.environ["MONGO_URL"])[os.environ["DB_NAME"]]

    sessions = {}
    async for s in db.mirror_v2_sessions.find({}, {"id": 1, "responses": 1}):
        values = [r["v"] for r in (s.get("responses") or {}).values() if isinstance(r, dict) and "v" in r]
        sessions[s["id"]] = len(set(values))

    keys = list(ARCHETYPES)
    varied_vectors, all_n, distinct_hist, flagged = [], 0, {}, []

    async for doc in db.results.find({}, {"session_id": 1, "instrument": 1, "result": 1}):
        distinct = sessions.get(doc.get("session_id"), 0)
        distinct_hist[distinct] = distinct_hist.get(distinct, 0) + 1
        low = distinct and distinct < VARIED_MIN_DISTINCT
        if low:
            flagged.append(doc["_id"])
        if doc.get("instrument") != "essential":
            continue
        all_n += 1
        if low or not distinct:
            continue
        scores = (doc.get("result") or {}).get("self", {}).get("archetype_scores") or {}
        if all(k in scores for k in keys):
            varied_vectors.append([scores[k]["percentage"] for k in keys])

    print(f"results total {sum(distinct_hist.values())} · essential {all_n}")
    print("distinct answer values per session:", dict(sorted(distinct_hist.items())))
    print(f"low-variation results (< {VARIED_MIN_DISTINCT} distinct): {len(flagged)}")

    # ---- 1. correlation matrix
    n = len(varied_vectors)
    print(f"\ncorrelation matrix, self lens, n={n}")
    cols = list(zip(*varied_vectors))
    offdiag = []
    print("        " + " ".join(f"{k[:5]:>6}" for k in keys))
    for i, k in enumerate(keys):
        row = []
        for j in range(len(keys)):
            r = 1.0 if i == j else pearson(cols[i], cols[j])
            row.append(r)
            if j > i:
                offdiag.append((abs(r), k, keys[j], r))
        print(f"{k[:7]:>7} " + " ".join(f"{v:6.2f}" for v in row))
    mags = [m for m, *_ in offdiag]
    print(f"\noff-diagonal |r|: mean {statistics.mean(mags):.2f} · median "
          f"{statistics.median(mags):.2f} · max {max(mags):.2f} · >=0.5: "
          f"{sum(1 for m in mags if m >= 0.5)}/{len(mags)}")
    for m, a, b, r in sorted(offdiag, reverse=True)[:6]:
        print(f"  {a} · {b}: {r:+.2f}")

    # ---- 3. MRD suppression, all vs varied
    from services import mrd as mrd_mod

    print("\nMRD flat-profile suppression rate")
    for instrument in ("personality", "eq"):
        rows = {"all": [], "varied": []}
        async for doc in db.results.find({"instrument": instrument}, {"session_id": 1, "result": 1}):
            r = doc.get("result") or {}
            r.setdefault("instrument", instrument)
            try:
                built = mrd_mod.build_mrd(r)
            except Exception:
                continue
            if not built:
                continue
            flat = any(s["flat_profile"] for s in built["scale_sets"])
            rows["all"].append(flat)
            d = sessions.get(doc.get("session_id"), 0)
            if d >= VARIED_MIN_DISTINCT:
                rows["varied"].append(flat)
        for scope, vals in rows.items():
            if vals:
                print(f"  {instrument:12} {scope:7} n={len(vals):5} flat-profile suppression "
                      f"{sum(vals) / len(vals):.3f}")

    if write_flags and flagged:
        res = await db.results.update_many(
            {"_id": {"$in": flagged}},
            {"$set": {"data_quality": "low_variation"}},
        )
        print(f"\nflagged {res.modified_count} results data_quality=low_variation")


if __name__ == "__main__":
    asyncio.run(main("--write-flags" in sys.argv))
