"""Generates host-level 301 rules for the new site from docs/redirect_map.json.

Writes:
  frontend/public/_redirects        Netlify/Cloudflare Pages style, 301
  docs/edge/nginx_redirects.conf    for an nginx/ingress host
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAP = os.path.join(ROOT, "docs", "redirect_map.json")
NETLIFY = os.path.join(ROOT, "frontend", "public", "_redirects")
NGINX = os.path.join(ROOT, "docs", "edge", "nginx_redirects.conf")

with open(MAP, encoding="utf-8") as fh:
    data = json.load(fh)

netlify = ["# Generated by scripts/build_redirects.py — do not edit by hand.", ""]
nginx = ["# Generated by scripts/build_redirects.py — include inside the ratherknow.com server block.", ""]

for src, dst in data["exact"].items():
    netlify.append(f"{src}  {dst}  301")
    nginx.append(f"location = {src} {{ return 301 {dst}$is_args$args; }}")

for rule in data["prefix"]:
    src, dst = rule["from"], rule["to"]
    if rule.get("keep_rest"):
        netlify.append(f"{src}*  {dst}:splat  301")
        nginx.append(f"location ^~ {src} {{ rewrite ^{src}(.*)$ {dst}$1 permanent; }}")
    else:
        netlify.append(f"{src}*  {dst}  301")
        nginx.append(f"location ^~ {src} {{ return 301 {dst}; }}")

# SPA fallback must come last so it never shadows a redirect.
netlify += ["", "/*  /index.html  200"]

with open(NETLIFY, "w", encoding="utf-8") as fh:
    fh.write("\n".join(netlify) + "\n")
with open(NGINX, "w", encoding="utf-8") as fh:
    fh.write("\n".join(nginx) + "\n")

print(f"wrote {len(data['exact'])} exact + {len(data['prefix'])} prefix rules")
print(f"  {NETLIFY}\n  {NGINX}")
